name: restudy_news
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  provider: ^4.1.2
  chopper: ^3.0.2
  json_annotation: ^3.0.1
  flutter_advanced_networkimage: ^0.7.0
  webview_flutter: ^0.3.22+1
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  path_provider:
  path:
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  chopper_generator: ^3.0.2
  json_serializable: ^3.3.0
  moor_generator: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "2e2e2e"

  fonts:
    - family: MPLUSRounded
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

adaptive_icon_background: "#212121"
adaptive_icon_foreground: "assets/images/ic_launcher.png"
